version : '3'
services:
  solr-app:
    image: solr:7.6
    ports:
      - "8983:8983"
    volumes:
      - ./src/solr_cores/IndianTowns:/opt/solr/server/solr/IndianTowns
      - ./src/solr_cores/TownCategory:/opt/solr/server/solr/TownCategory

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - solr-app
